from enum import Enum


class CaseStatus(str, Enum):
    NEW = "NEW"
    WAITING_CLIENT = "WAITING_CLIENT"
    WAITING_MODERATOR = "WAITING_MODERATOR"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class CaseEventType(str, Enum):
    CASE_CREATED = "CASE_CREATED"
    CLIENT_REQUEST_SENT = "CLIENT_REQUEST_SENT"
    CLIENT_REPLY_RECEIVED = "CLIENT_REPLY_RECEIVED"
    MODERATOR_NOTIFIED = "MODERATOR_NOTIFIED"
    CLIENT_REMINDER_SENT = "CLIENT_REMINDER_SENT"
    MODERATOR_REMINDER_SENT = "MODERATOR_REMINDER_SENT"
    CASE_ESCALATED = "CASE_ESCALATED"
    MODERATOR_CHANGED = "MODERATOR_CHANGED"
    USER_ANSWER_CONFIRMED = "USER_ANSWER_CONFIRMED"
    CASE_CLOSED = "CASE_CLOSED"
    CASE_CANCELLED = "CASE_CANCELLED"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    DELIVERY_RETRIED = "DELIVERY_RETRIED"
